import { chromium } from 'playwright-core'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const ctx = await browser.newContext({ viewport: { width: 390, height: 760 }, isMobile: true, hasTouch: true })
await ctx.route(/^(?!http:\/\/localhost).*/, (r) => r.abort())
await ctx.addInitScript(() => { localStorage.setItem('tomningskartan.introSeen', '1'); localStorage.setItem('tomningskartan.view', JSON.stringify({ lat: 58.2730122, lon: 12.3211748, zoom: 16 })) })
const page = await ctx.newPage()
page.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await page.goto('http://localhost:4173/'); await page.waitForTimeout(2500)
const chip = page.locator('[data-service="gasol_pafyllning"]').first()
await chip.click(); await page.waitForTimeout(1500)
console.log('aria-pressed:', await chip.getAttribute('aria-pressed'), '| marker-icons:', await page.locator('.leaflet-marker-icon').count(), '| pins:', await page.locator('.pin').count(), '| status:', await page.locator('.status-bar, .status').first().innerText().catch(()=>'-'))
console.log('map center:', await page.evaluate(() => JSON.stringify(localStorage.getItem('tomningskartan.view'))))
await page.screenshot({ path: '/tmp/claude-0/-home-user-PJfrance/6140915e-86bc-5bdf-9a99-cd26fe969797/scratchpad/mobil-chip.png' })
await browser.close()
